-- Authorization codes for transfer protocol
-- Each code is single-use, generated by admin for a user + service.
-- No time-based expiry (codes remain valid until used).
-- Admin can regenerate (deletes prior unused code) via the admin UI.

CREATE TABLE IF NOT EXISTS authorization_codes (
  id          SERIAL PRIMARY KEY,
  user_id     INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  service     TEXT    NOT NULL CHECK (service IN ('bond','pof','blocked','lc','apg','bg')),
  code        TEXT    NOT NULL,
  used        BOOLEAN NOT NULL DEFAULT false,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_auth_codes_user_service ON authorization_codes (user_id, service);